default: &default
  types: [
    "aaib_report",
    "about",
    "about_our_services",
    "access_and_opening",
    "announcement",
    "answer",
    "asylum_support_decision",
    "authored_article",
    "business_support",
    "business_support_finder",
    "calculator",
    "calendar",
    "campaign",
    "case_study",
    "closed_consultation",
    "cma_case",
    "complaints_procedure",
    "consultation_outcome",
    "contact",
    "corporate_report",
    "correspondence",
    "countryside_stewardship_grant",
    "decision",
    "detailed_guide",
    "dfid_research_output",
    "document_collection",
    "drug_safety_update",
    "employment_tribunal_decision",
    "equality_and_diversity",
    "esi_fund",
    "fatality_notice",
    "finder",
    "foi_release",
    "form",
    "generic_with_external_related_links",
    "government_response",
    "guidance",
    "guide",
    "help_page",
    "hmrc_manual",
    "hmrc_manual_section",
    "impact_assessment",
    "independent_report",
    "international_development_fund",
    "international_treaty",
    "licence",
    "license_finder",
    "local_transaction",
    "maib_report",
    "manual",
    "manual_section",
    "map",
    "media_enquiries",
    "medical_safety_alert",
    "membership",
    "ministerial_role",
    "national",
    "national_statistics",
    "national_statistics_announcement",
    "news_story",
    "notice",
    "official",
    "official_statistics",
    "official_statistics_announcement",
    "open_consultation",
    "oral_statement",
    "organisation",
    "our_energy_use",
    "our_governance",
    "person",
    "personal_information_charter",
    "petitions_and_campaigns",
    "place",
    "placeholder",
    "placeholder_organisation",
    "policy",
    "policy_area",
    "policy_paper",
    "press_release",
    "procurement",
    "programme",
    "promotional",
    "publication_scheme",
    "raib_report",
    "recruitment",
    "redirect",
    "regulation",
    "research",
    "service_manual_guide",
    "service_manual_topic",
    "service_standard_report",
    "simple_smart_answer",
    "smart_answer",
    "social_media_use",
    "specialist_document",
    "speech",
    "staff_update",
    "statistical_data_set",
    "statistics",
    "statistics_announcement",
    "statutory_guidance",
    "tax_tribunal_decision",
    "terms_of_reference",
    "topical_event",
    "transaction",
    "transparency",
    "travel_advice",
    "utaac_decision",
    "welsh_language_scheme",
    "world_location_news_article",
    "written_statement"
  ]

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
